server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always

#Configurando o nivel de log que sera exibido no console quando a aplicação for iniciada e utilizada
logging:
  level:
    br.com.wepdev.authuser: TRACE
    root: info
    org.springframework.web: DEBUG
    org.hibernate: info
